"""Regenerates Utils/Tex/Bc7Tables.cs from a reference BC7 decoder.

    python generate_bc7_tables.py [path/to/bc7decomp.cpp]

Typing those tables by hand is how a transposed row got into the third-subset anchor table, which
broke only the blocks using those partitions. Parsing the authoritative source removes the
transcription step, and the invariant checks below fail loudly if the parse goes wrong.

The default source is the copy of Rich Geldreich's bc7decomp.cpp vendored in the Proteus repo next
door; pass a path if yours lives elsewhere. Run compare_against_reference.py afterwards.
"""
import io
import os
import re
import sys

DEFAULT_SRC = r"E:/repos/Proteus/Proteus/native/src/bc7decomp.cpp"
SRC = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
DST = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "..", "Utils", "Tex", "Bc7Tables.cs")

if not os.path.exists(SRC):
    raise SystemExit(f"No reference decoder at {SRC}\n"
                     f"Pass the path to bc7decomp.cpp as the first argument.")

text = io.open(SRC, encoding="utf-8", errors="replace").read()


def array(name):
    m = re.search(re.escape(name) + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\}\s*;", text, re.S)
    if not m:
        raise SystemExit(f"could not find {name}")
    return [int(v) for v in re.findall(r"-?\d+", m.group(1))]


part2 = array("g_bc7_partition2")
part3 = array("g_bc7_partition3")
anchor2 = array("g_bc7_table_anchor_index_second_subset")
anchor3a = array("g_bc7_table_anchor_index_third_subset_1")
anchor3b = array("g_bc7_table_anchor_index_third_subset_2")
w2 = array("g_bc7_weights2")
w3 = array("g_bc7_weights3")
w4 = array("g_bc7_weights4")

assert len(part2) == 64 * 16, len(part2)
assert len(part3) == 64 * 16, len(part3)
for name, a, n in (("anchor2", anchor2, 64), ("anchor3a", anchor3a, 64), ("anchor3b", anchor3b, 64)):
    assert len(a) == n, f"{name}: {len(a)}"
assert (len(w2), len(w3), len(w4)) == (4, 8, 16)

# The invariants the decoder depends on, checked here as well as in the harness: an anchor belongs
# to the subset it anchors, the three anchors of a block are distinct, and every subset is used.
for p in range(64):
    row2 = part2[p * 16:(p + 1) * 16]
    row3 = part3[p * 16:(p + 1) * 16]
    assert set(row2) == {0, 1}, p
    assert set(row3) == {0, 1, 2}, p
    assert row2[anchor2[p]] == 1 and anchor2[p] != 0, p
    assert row3[anchor3a[p]] == 1 and anchor3a[p] != 0, p
    assert row3[anchor3b[p]] == 2 and anchor3b[p] != 0, p
    assert anchor3a[p] != anchor3b[p], p
print("reference tables pass every invariant")


def rows(values, per_row, width):
    out = []
    for i in range(0, len(values), per_row):
        chunk = ", ".join(f"{v:{width}}" for v in values[i:i + per_row])
        out.append("            " + chunk + ",")
    return "\n".join(out)


def partition_rows(values):
    out = []
    for p in range(0, 64, 2):
        a = ",".join(str(v) for v in values[p * 16:(p + 1) * 16])
        b = ",".join(str(v) for v in values[(p + 1) * 16:(p + 2) * 16])
        out.append(f"            {{{a}}}, {{{b}}},")
    return "\n".join(out)


cs = f'''namespace Pickles_Playlist_Editor.Utils.Tex
{{
    /// <summary>
    /// The fixed lookup tables BC7 decoding needs: which texel belongs to which subset for each of
    /// the 64 partitions, which texel of a subset carries a one-bit-short index, and the
    /// interpolation weights.
    ///
    /// GENERATED by devtools/TexHarness/generate_bc7_tables.py from a reference decoder, not typed
    /// out — edit that script rather than this file. A single wrong entry here corrupts only the
    /// blocks that happen to use that partition, which is exactly the kind of fault that survives
    /// eyeballing a picture; one did, until the harness caught it. TexHarness --codeccheck
    /// re-checks the anchors against the partitions, and compare_against_reference.py then decodes
    /// thousands of random blocks against an independent decoder.
    /// </summary>
    internal static class Bc7Tables
    {{
        /// <summary>Subset of each texel, for the 64 two-subset partitions.</summary>
        public static readonly byte[,] Partition2 =
        {{
{partition_rows(part2)}
        }};

        /// <summary>Subset of each texel, for the 64 three-subset partitions.</summary>
        public static readonly byte[,] Partition3 =
        {{
{partition_rows(part3)}
        }};

        /// <summary>Texel carrying the short index for subset 1, in a two-subset partition.</summary>
        public static readonly byte[] Anchor2 =
        {{
{rows(anchor2, 16, 2)}
        }};

        /// <summary>Texel carrying the short index for subset 1, in a three-subset partition.</summary>
        public static readonly byte[] Anchor3First =
        {{
{rows(anchor3a, 16, 2)}
        }};

        /// <summary>Texel carrying the short index for subset 2, in a three-subset partition.</summary>
        public static readonly byte[] Anchor3Second =
        {{
{rows(anchor3b, 16, 2)}
        }};

        /// <summary>Interpolation weights, indexed by index bit count then by index.</summary>
        public static readonly byte[][] Weights =
        {{
            System.Array.Empty<byte>(),
            System.Array.Empty<byte>(),
            new byte[] {{ {", ".join(str(v) for v in w2)} }},
            new byte[] {{ {", ".join(str(v) for v in w3)} }},
            new byte[] {{ {", ".join(str(v) for v in w4)} }},
        }};
    }}
}}
'''

io.open(DST, "w", encoding="utf-8-sig", newline="\r\n").write(cs)
print("wrote", DST)
